# Generated by Django 5.0.3 on 2024-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('up', models.DateField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=50)),
                ('asgn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('up', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('up', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Leture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('up', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('up', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('p_phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('up', models.DateField(max_length=10)),
            ],
        ),
    ]
