# Generated by Django 5.0.3 on 2024-03-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='title',
            new_name='titles',
        ),
    ]
